sudo: required

services:
  - docker

install: []

branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/ # Tag in the format vX.Y.Z
    - feature/dockerization

script:
  - docker build -t guglielmino/mosquitto-pushetta-auth-plugin .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: feature/dockerization
