sudo: required

services:
  - docker

install: []

branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/ # Tag in the format vX.Y.Z

script:
  - docker build -t guglielmino/mosquitto-pushetta-auth-plugin:latest  -t guglielmino/mosquitto-pushetta-auth-plugin:$TRAVIS_TAG .
deploy:
  provider: script
  script: bash docker_push $TRAVIS_TAG
  on:
    branch: /v\d+\.\d+[a-z]/
